modLoader="javafml" #mandatory

loaderVersion="[28,)" #mandatory

authors="Shadows_of_Fire" #optional

[[mods]] #mandatory

modId="hydrogel" #mandatory

version="${file.jarVersion}" #mandatory

displayName="HydroGel" #mandatory

license="MIT License" #mandatory

description='''
Clicc.
'''

[[dependencies.hydrogel]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32.0.106,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.hydrogel]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hydrogel]]
    modId="placebo"
    mandatory=true
    versionRange="[4.1,)"
    ordering="NONE"
    side="BOTH"